apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaplug
  namespace: metaplug
spec:
  selector:
    matchLabels:
      app: plug
  replicas: 3
  template:
    metadata:
      labels:
        app: plug
    spec:
      volumes:
      - name: bitmount
        hostPath:
          path: /mnt
          type: Directory
      containers: 
      - name: plug
        image: gwolf3/metaplug-demo:0.0.3
        imagePullPolicy: Always
        env:
        - name: BITCOM
          value: '19HxigV4QyBv3tHpQVcUEQyq1pzZVdoAut'
        ports:
        - containerPort: 57575
          name: http
        volumeMounts:
        - name: bitmount 
          mountPath: /root

---

apiVersion: v1
kind: Service
metadata:
  name: metaplug-http
  namespace: metaplug
spec:
  selector:
    app: plug
  ports:
  - protocol: TCP
    targetPort: 57575
    port: 8080
    name: http
  type: LoadBalancer
